### PR TITLE
Add JSON output support

### PR DESCRIPTION
**Pull request by DangerOnTheRanger**
This PR adds an `--output/-o json` switch that outputs linting errors as JSON. Since this is a user-facing/command-line tool change, the tests will be added as a part of #2.

### CODE REVIEW

File: cmd/celvet/main.go [hunk 1]
```diff
@@ -31,7 +33,8 @@ import (
 
 func main() {
 
-	humanReadable := flag.BoolP("human-readable", "r", true, "print out values in human-readable formats")
+	humanReadable := flag.BoolP("human-readable", "r", true, "print out values in human-readable formats (only applies if --json/-j is not passed)")
+	useJSON := flag.BoolP("json", "j", false, "emit linter errors as JSON")
```
Comment (jpbetz) [inline cmd/celvet/main.go:37]: Future proof against other output formats?  Maybe `--output=json` (`-o json`) like kubectl does?

File: cmd/celvet/main.go [hunk 2]
```diff
@@ -81,13 +84,43 @@ func main() {
 	}
 
 	limitErrors := celvet.CheckMaxLimits(structural)
+	costErrors, compileErrors := celvet.CheckExprCost(structural)
+	if *useJSON {
+		emitJSON(limitErrors, costErrors, compileErrors)
+	} else {
+		emitNormal(limitErrors, costErrors, compileErrors, *humanReadable)
```
Comment (jpbetz) [inline cmd/celvet/main.go:91]: emitText?

File: cmd/celvet/main.go [hunk 3]
```diff
@@ -81,13 +84,43 @@ func main() {
...
+	buf := bytes.NewBuffer(nil)
+	encoder := json.NewEncoder(buf)
+	encoder.SetEscapeHTML(false)
+	output := JSONOutput{LimitErrors: limitErrors, CostErrors: costErrors, CompileErrors: compileErrors}
+	err := encoder.Encode(output)
+	if err != nil {
+		fmt.Fprintf(os.Stderr, "error generating JSON output: %s\n", err)
+	}
+	// use Printf instead of Println to prevent a redundant newline from being output
+	fmt.Printf("%s", buf.Bytes())
```
Comment (jpbetz) [inline cmd/celvet/main.go:115]: By redundant to you mean there were two newlines being printed when Println was used?

File: cmd/celvet/main.go [hunk 4]
```diff
@@ -31,7 +33,8 @@ import (
 
 func main() {
 
-	humanReadable := flag.BoolP("human-readable", "r", true, "print out values in human-readable formats")
+	humanReadable := flag.BoolP("human-readable", "r", true, "print out values in human-readable formats (only applies if --json/-j is not passed)")
```
Comment (jpbetz) [inline cmd/celvet/main.go:36]: Why disallow -r for json? It's not immediately obvious to me why that wouldn't be allowed.

File: cmd/celvet/main.go [hunk 5]
```diff
@@ -81,13 +84,43 @@ func main() {
...
+	if len(limitErrors)+len(costErrors)+len(compileErrors) > 0 {
+		os.Exit(1)
+	}
+}
+
+func emitJSON(limitErrors []error, costErrors []*celvet.CostError, compileErrors []error) {
+	type JSONOutput struct {
+		LimitErrors   []error             `json:"limitErrors"`
+		CostErrors    []*celvet.CostError `json:"costErrors"`
+		CompileErrors []error             `json:"compileErrors"`
```
Comment (jpbetz) [inline cmd/celvet/main.go:103]: Shouldn't compile and limit errors have paths somewhere too?

**Review by jpbetz — CHANGES_REQUESTED** [review]

File: cmd/celvet/main.go (hunk 3 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go:115]: Right - looking at the contents of `buf`, the last character is `10`\`\n`, which makes me think that the `json` module inserts one itself when encoding.

File: cmd/celvet/main.go (hunk 4 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go:36]: At present `-r` only affects `CostError.HumanReadableError()`, which is only used during text output, so it technically could be used in conjunction with JSON, but it wouldn't do anything.

File: cmd/celvet/main.go (hunk 2 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: That's a much better name - fixed!

File: cmd/celvet/main.go (hunk 1 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Makes sense, fixed

File: cmd/celvet/main.go (hunk 4 above)
Comment (jpbetz) [reply cmd/celvet/main.go:36]: `-r` still documentation refers to `--json` which doesn't exist any more.

File: cost.go [hunk 6]
```diff
@@ -28,9 +28,9 @@ type CostError struct {
 	// Path represents the path to the schema node containing the expression.
 	// The path-generating implementation here is different than the one
 	// in Kubernetes and will generate slightly different-looking output.
-	Path string
+	Path string `json:"path"`
 	// Cost represents the cost of the expression. This is a unitless value.
-	Cost uint64
+	Cost uint64 `json:"cost"`
```
Comment (jpbetz) [inline cost.go:33]: Should the cost limit that was exceeded also be included?

File: cmd/celvet/main.go [hunk 7]
```diff
@@ -81,23 +92,58 @@ func main() {
...
+
+func emitJSON(limitErrors []error, costErrors []*celvet.CostError, compileErrors []*celvet.CompilationError, otherErrors []error) {
+	type JSONOutput struct {
+		LimitErrors   []error                    `json:"limitErrors"`
+		CostErrors    []*celvet.CostError        `json:"costErrors"`
+		CompileErrors []*celvet.CompilationError `json:"compileErrors"`
+		OtherErrors   []string                   `json:"otherErrors"`
+	}
+
+	buf := bytes.NewBuffer(nil)
```
Comment (jpbetz) [inline cmd/celvet/main.go:115]: nit: No need to accumulate the json output in memory before printing.  Just use something like `enc := json.NewEncoder(os.Stdout)` ?

File: cmd/celvet/main.go [hunk 8]
```diff
@@ -81,23 +92,58 @@ func main() {
...
+	}
+
+	if len(limitErrors)+len(costErrors)+len(compileErrors) > 0 {
+		os.Exit(1)
+	}
+}
+
+func emitJSON(limitErrors []error, costErrors []*celvet.CostError, compileErrors []*celvet.CompilationError, otherErrors []error) {
+	type JSONOutput struct {
+		LimitErrors   []error                    `json:"limitErrors"`
```
Comment (jpbetz) [inline cmd/celvet/main.go:109]: Why is LimitError just a plain error? Should `limitError` be used here or should paths be otherwise attached?

File: cmd/celvet/main.go [hunk 9]
```diff
@@ -81,23 +92,58 @@ func main() {
...
+		CostErrors    []*celvet.CostError        `json:"costErrors"`
+		CompileErrors []*celvet.CompilationError `json:"compileErrors"`
+		OtherErrors   []string                   `json:"otherErrors"`
```
Comment (jpbetz) [inline cmd/celvet/main.go:112]: What is OtherErrors for?  Is there a more descriptive name that could be used?  Is this for linter failures?

File: cmd/celvet/main.go [hunk 10]
```diff
@@ -81,23 +92,58 @@ func main() {
...
+		emitText(limitErrors, costErrors, compileErrors, otherErrors, *humanReadable)
+	}
+
+	if len(limitErrors)+len(costErrors)+len(compileErrors) > 0 {
+		os.Exit(1)
+	}
+}
+
+func emitJSON(limitErrors []error, costErrors []*celvet.CostError, compileErrors []*celvet.CompilationError, otherErrors []error) {
+	type JSONOutput struct {
```
Comment (jpbetz) [inline cmd/celvet/main.go:108]: Mark all fields that are optional and lists that can be empty with `omitempty` to make json output more compact/readable?

File: limits.go [hunk 11]
```diff
@@ -28,8 +28,8 @@ const (
 )
 
 type limitError struct {
-	Name string
-	Type schemaType
+	Name string     `json:"path"`
+	Type schemaType `json:"type"`
```
Comment (jpbetz) [inline limits.go:32]: Why return numeric schema type values to users?

File: cmd/celvet/main.go (hunk 8 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Should be fixed now - `LimitError` is used instead.

File: cmd/celvet/main.go (hunk 10 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go:108]: Gotcha, fixed

File: limits.go (hunk 11 above)
Comment (DangerOnTheRanger) [reply limits.go]: Fixed - I had to add `MarshalJSON` functions for all errors as a part of resolving merge conflicts with #6, and the schema type is now output as a string instead.

File: cmd/celvet/main.go (hunk 4 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Whoops, fixed the documentation referring to the old `--json` flag and clarified that it applies only to text output.

File: cmd/celvet/main.go (hunk 9 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: `OtherErrors` is for errors returned by `cel.Compile` that aren't related to compilation errors, so it's for internal/non-linting-related failures. Maybe `InternalErrors` would be a better name?

File: cost.go (hunk 6 above)
Comment (DangerOnTheRanger) [reply cost.go]: Makes sense, the limit probably won't be visible/known by end-users otherwise - fixed

File: cmd/celvet/main.go (hunk 7 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Whoops, you're right - fixed

File: cmd/celvet/main.go [hunk 12]
```diff
@@ -81,23 +91,55 @@ func main() {
...
+		LimitErrors   []*celvet.LimitError       `json:"limitErrors,omitempty"`
+		CostErrors    []*celvet.CostError        `json:"costErrors,omitempty"`
+		CompileErrors []*celvet.CompilationError `json:"compileErrors,omitempty"`
+		OtherErrors   []string                   `json:"otherErrors,omitempty"`
+	}
+
+	encoder := json.NewEncoder(os.Stdout)
+	encoder.SetEscapeHTML(false)
+	strOtherErrors := make([]string, 0)
```
Comment (jpbetz) [inline cmd/celvet/main.go:116]: Since the length of `strOtherErrors` will be the same as `otherErrors`, it is more idiomatic to use `make([]string, len(otherErrors)` and then  fill the array directly (no append).

File: cmd/celvet/main.go [hunk 13]
```diff
@@ -81,23 +91,55 @@ func main() {
...
+	for _, err := range otherErrors {
+		strOtherErrors = append(strOtherErrors, err.Error())
+	}
+	output := JSONOutput{LimitErrors: limitErrors, CostErrors: costErrors, CompileErrors: compileErrors, OtherErrors: strOtherErrors}
+	err := encoder.Encode(output)
+	if err != nil {
+		fmt.Fprintf(os.Stderr, "error generating JSON output: %s\n", err)
+		os.Exit(1)
```
Comment (jpbetz) [inline cmd/celvet/main.go:124]: I wasn't expecting the function to exit. Consider only exiting in main and limiting output here to json. If there is an error is serializing json, return and error and let main handle it.

File: cmd/celvet/main.go [hunk 14]
```diff
@@ -81,23 +91,55 @@ func main() {
 	}
 
 	limitErrors := celvet.CheckMaxLimits(structural)
+	costErrors, compileErrors, otherErrors := celvet.CheckExprCost(structural)
```
Comment (jpbetz) [inline cmd/celvet/main.go:94]: This trio of error slices is used quite a bit in the code, consider introducing a type for it?  Type could also have a `hasErrors` function that returns true if any of the three slices is len > 0.

File: limits.go [hunk 15]
```diff
@@ -55,6 +56,28 @@ func (l *LimitError) Error() string {
...
 }
 
+// MarshalJSON returns the LimitError in JSON format.
+func (l *LimitError) MarshalJSON() ([]byte, error) {
+	var typeString string
+	switch l.Type {
+	case SchemaTypeMap:
+		typeString = "map"
+	case SchemaTypeList:
+		typeString = "list"
```
Comment (jpbetz) [inline limits.go:66]: Will this make sense to users?  OpenAPIv3 has "array" and "object" types  not "map" and "list" ("object with additionalProperties" is how what most developers consider a "map" are represented in OpenAPIv3).

**Review by jpbetz — CHANGES_REQUESTED** [review]

File: cmd/celvet/main.go (hunk 12 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: That makes a lot more sense, thanks - fixed

File: cmd/celvet/main.go (hunk 9 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: (marking this as fixed this since `OtherErrors` has been renamed to `InternalErrors`)

File: limits.go (hunk 15 above)
Comment (DangerOnTheRanger) [reply limits.go]: I was wondering how weird it might be to receive a "missing limit" error on an object/how best to phrase it - I've switched the wording/constants to use "array" and "object."

File: cmd/celvet/main.go (hunk 13 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Right, now `emitJSON` returns the error and only `main` exits - fixed

File: cmd/celvet/main.go (hunk 14 above)
Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Fixed - I've added a `LinterErrors` struct that's used throughout the codebase now.

File: cmd/celvet/main.go [hunk 16]
```diff
@@ -80,24 +90,45 @@ func main() {
...
-	costErrors, compileErrors := celvet.CheckExprCost(structural)
-	for _, lintError := range costErrors {
-		if *humanReadable {
+	if lintErrs.HasErrors() {
+		os.Exit(1)
+	}
+}
+
+func emitJSON(l *celvet.LinterErrors) error {
+	encoder := json.NewEncoder(os.Stdout)
```
Comment (jpbetz) [inline cmd/celvet/main.go:112]: Why stdout for JSON format and stderr for text format?

Comment (DangerOnTheRanger) [reply cmd/celvet/main.go:112]: `stderr` for `emitText` was a mistake on my part, sorry (or at least if it wasn't, I can't recall the rationale/didn't record it) - fixed

File: cmd/celvet/main.go [hunk 17]
```diff
@@ -80,24 +90,45 @@ func main() {
...
+	encoder.SetEscapeHTML(false)
+	return encoder.Encode(l)
+}
+
+func emitText(l *celvet.LinterErrors, humanReadable bool) {
+	for _, lintError := range l.LimitErrors {
+		fmt.Fprintf(os.Stdout, "%s\n", lintError)
```
Comment (jpbetz) [inline cmd/celvet/main.go:119]: check if an error is returned in all calls to `Fprintf` instead of discarding them?

Comment (DangerOnTheRanger) [reply cmd/celvet/main.go]: Fixed - I've added an error check on all calls that weren't immediately followed by an `os.Exit(1)`, so now there's checks on the custom `flag.Usage` in addition to the entirety of `emitText`.

**Comment by jpbetz** [comment]
LGTM
